"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Badge, EmptyState, inputClassName } from "@/components/ui";
type Exercise = { id: string; name: string; muscleGroup: string; unit: "REPS" | "SECONDS"; instructions: string | null; description: string | null; notes: string | null; isSystem: boolean };
export function ExerciseDirectory({ exercises }: { exercises: Exercise[] }) {
  const [query,setQuery]=useState(''); const [group,setGroup]=useState('');
  const groups=[...new Set(exercises.map(e => e.muscleGroup))];
  const filtered=useMemo(() => { const normalize=(v:string) => v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(); return exercises.filter(e => (!group || e.muscleGroup===group) && normalize(`${e.name} ${e.muscleGroup}`).includes(normalize(query))); },[exercises,group,query]);
  return <section className="overflow-hidden rounded-xl border border-[#dfe3e6] bg-white"><div className="grid gap-4 border-b border-[#dfe3e6] p-5 sm:grid-cols-2"><label className="text-sm font-semibold">Buscar exercício<input type="search" value={query} onChange={e=>setQuery(e.target.value)} className={inputClassName} placeholder="Nome ou grupo muscular" /></label><label className="text-sm font-semibold">Grupo muscular<select value={group} onChange={e=>setGroup(e.target.value)} className={inputClassName}><option value="">Todos os grupos</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label></div><p className="px-5 py-3 text-sm text-[#64707d]" role="status">{filtered.length} exercícios</p>{!filtered.length ? <EmptyState title="Nenhum exercício encontrado" description="Ajuste a busca ou cadastre um exercício para sua academia." /> : <div className="divide-y divide-[#edf0f2]">{filtered.map(e=><details key={e.id}><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3 px-5 py-4"><div><h2 className="font-bold">{e.name}</h2><p className="mt-1 text-sm text-[#64707d]">{e.muscleGroup} · {e.unit==='SECONDS' ? 'Por tempo (segundos)' : 'Por repetições'}</p></div><Badge tone={e.isSystem ? 'neutral' : 'accent'}>{e.isSystem?'Global':'Da academia'}</Badge></summary><div className="space-y-3 bg-[#fafafa] p-5 text-sm leading-6 text-[#64707d]"><p>{e.instructions || e.description || 'Sem instruções cadastradas.'}</p>{e.notes && <p>{e.notes}</p>}{!e.isSystem && <Link href={`/exercises/${e.id}/edit`} className="secondary-button">Editar exercício</Link>}</div></details>)}</div>}</section>;
}
