import { Role } from "@prisma/client";
import { Heart, MessageCircle, ShieldCheck } from "lucide-react";
import { createCommunityPost, commentCommunityPost, moderateCommunityComment, moderateCommunityPost, toggleCommunityLike } from "@/app/actions/community";
import { ActionForm } from "@/components/action-form";
import { PageHeader, EmptyState, inputClassName } from "@/components/ui";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const metadata = { title: "Comunidade" };
export default async function CommunityPage({ searchParams }: { searchParams: Promise<{ before?: string }> }) {
  const viewer = await requireRole();
  const { before } = await searchParams;
  const cutoff = before && !Number.isNaN(Date.parse(before)) ? new Date(before) : null;
  const posts = await prisma.communityPost.findMany({ where: { organizationId: viewer.organizationId, ...(viewer.role !== Role.ADMIN ? { hidden: false } : {}), ...(cutoff ? { createdAt: { lt: cutoff } } : {}) }, include: { author: { include: { user: { select: { name: true } } } }, comments: { where: { hidden: false }, orderBy: { createdAt: "asc" }, take: 15, include: { author: { include: { user: { select: { name: true } } } } } }, likes: { where: { memberId: viewer.id }, select: { memberId: true } }, _count: { select: { likes: true, comments: { where: { hidden: false } } } } }, orderBy: { createdAt: "desc" }, take: 16 });
  const more = posts.length > 15;
  return <div className="mx-auto max-w-3xl space-y-7"><PageHeader eyebrow="Conexões da academia" title="Comunidade" description="Compartilhe conquistas e incentive colegas dentro da sua academia." />
    <div className="flex items-start gap-3 border-l-4 border-[#79a6cb] bg-[#edf5fc] p-4 text-sm text-[#24425f]"><ShieldCheck className="mt-0.5 size-5 shrink-0" /><p>Esta área é visível para membros da mesma academia. Evite publicar localização, dados de saúde, fotos de terceiros ou informações particulares. A administração pode moderar publicações.</p></div>
    <ActionForm action={createCommunityPost} className="space-y-3 border border-[#dfe3e6] bg-white p-5"><label htmlFor="community-body" className="font-semibold">O que você gostaria de compartilhar?</label><textarea id="community-body" name="body" minLength={3} maxLength={700} rows={3} required placeholder="Ex.: concluí meu primeiro mês de treinos!" className={inputClassName} /><div className="flex justify-end"><button className="primary-button">Publicar</button></div></ActionForm>
    {!posts.length ? <EmptyState title="Comece a conversa" description="As publicações da sua academia aparecerão aqui." /> : <section className="space-y-4" aria-label="Publicações da academia">{posts.slice(0,15).map(post => <article key={post.id} className={`overflow-hidden border bg-white ${post.hidden ? "border-amber-300 opacity-75" : "border-[#dfe3e6]"}`}><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{post.author.user.name}</p><p className="text-xs text-[#64707d]">{post.createdAt.toLocaleString("pt-BR")} · {post.author.role === Role.STUDENT ? "Aluno" : post.author.role === Role.PROFESSOR ? "Professor" : post.author.role === Role.NUTRITIONIST ? "Nutricionista" : "Academia"}</p></div>{(viewer.role === Role.ADMIN || viewer.id === post.authorId) && <ActionForm action={moderateCommunityPost}><input type="hidden" name="postId" value={post.id} /><input type="hidden" name="hidden" value={String(!post.hidden)} /><button className="text-xs font-semibold text-[#64707d] hover:underline">{post.hidden ? "Restaurar" : "Ocultar"}</button></ActionForm>}</div><p className="mt-4 whitespace-pre-line break-words leading-7 text-[#27313a]">{post.body}</p></div>
      {!post.hidden && <div className="border-t border-[#edf0f2] px-5 py-3"><div className="flex items-center gap-4 text-sm"><ActionForm action={toggleCommunityLike}><input type="hidden" name="postId" value={post.id} /><button aria-label={post.likes.length ? "Remover curtida" : "Curtir publicação"} className={`inline-flex min-h-11 items-center gap-1 font-semibold ${post.likes.length ? "text-[var(--accent)]" : "text-[#64707d]"}`}><Heart className={`size-4 ${post.likes.length ? "fill-current" : ""}`} /> {post._count.likes}</button></ActionForm><span className="inline-flex items-center gap-1 text-[#64707d]"><MessageCircle className="size-4" /> {post._count.comments} comentários</span></div>
      {post.comments.length > 0 && <ul className="mt-3 divide-y divide-[#edf0f2]">{post.comments.map(comment => <li key={comment.id} className="flex items-start justify-between gap-2 py-3 text-sm"><div><strong>{comment.author.user.name}</strong><p className="mt-1 whitespace-pre-line break-words text-[#465568]">{comment.body}</p></div>{(viewer.role === Role.ADMIN || viewer.id === comment.authorId) && <ActionForm action={moderateCommunityComment}><input type="hidden" name="commentId" value={comment.id} /><button className="text-xs text-[#64707d] hover:underline">Ocultar</button></ActionForm>}</li>)}</ul>}
      {post._count.comments > post.comments.length && <p className="text-xs text-[#64707d]">Mostrando os primeiros {post.comments.length} comentários.</p>}
      <ActionForm action={commentCommunityPost} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="postId" value={post.id} /><input name="body" minLength={3} maxLength={700} required aria-label="Escreva um comentário" placeholder="Escreva um comentário" className={`${inputClassName} mt-0 min-w-[200px] flex-1`} /><button className="secondary-button">Comentar</button></ActionForm></div>}
    </article>)}</section>}
    {more && <a href={`/community?before=${encodeURIComponent(posts[14].createdAt.toISOString())}`} className="secondary-button">Ver publicações anteriores</a>}
  </div>;
}
